development:
  adapter: redis
  url: redis://localhost:6379/2
  channel_prefix: chat_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chat_production
